# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soogikohad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=8)),
                ('eelroad', models.IntegerField(default=0)),
                ('supid', models.IntegerField(default=0)),
                ('praed', models.IntegerField(default=0)),
                ('magustoidud', models.IntegerField(default=0)),
                ('joogid', models.IntegerField(default=0)),
                ('kohvilaud', models.IntegerField(default=0)),
            ],
        ),
    ]
